version: "3.9"

services:
  db:
    image: postgres:16
    container_name: trilhas_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ../api
    container_name: trilhas_api
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  worker-pre:
    build: ../workers/worker-pre
    container_name: worker_pre
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  worker-rec:
    build: ../workers/worker-rec
    container_name: worker_rec
    restart: always
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: